name: Docker Image CI for GHCR

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    env:
      APP_NAME: easy-pr-frontend
      COMMIT_ID: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Login
        run: |
          docker login --username ${{ vars.CI_REGISTRY_USER }} --password ${{ vars.CI_REGISTRY_PAT }} ${{ vars.CI_REGISTRY }}

      - name: Build Docker Image
        run: |
          echo "${{ vars.ENV }}" > .env
          BUILD_TAG=${{ vars.CI_REGISTRY }}/vajra-technology/${{ env.APP_NAME }}:${{ env.COMMIT_ID }}
          BUILD_TAG_LATEST=${{ vars.CI_REGISTRY }}/vajra-technology/${{ env.APP_NAME }}:latest
          docker build . --tag $BUILD_TAG --tag $BUILD_TAG_LATEST

      - name: Push Docker Image
        run: |
          BUILD_TAG=${{ vars.CI_REGISTRY }}/vajra-technology/${{ env.APP_NAME }}:${{ env.COMMIT_ID }}
          BUILD_TAG_LATEST=${{ vars.CI_REGISTRY }}/vajra-technology/${{ env.APP_NAME }}:latest
          docker push $BUILD_TAG
          docker push $BUILD_TAG_LATEST

